on: push

name: Generate Changelog
jobs:
  docup:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the Changelog
        uses: r26d/generate-changelog@v1.0.0
        with:
          file: "CHANGELOG.md"