on: 
  push:
    branches: master

name: Update Docs
jobs:
  docup:
    runs-on: ubuntu-latest
    steps:
      - name: Update Docs
        uses: dops-cli/docs-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
