on:
  push:
    branches: master

name: Update Docs
jobs:
  docup:
    if: "!contains(github.event.head_commit.message, 'autoupdate')"
    runs-on: ubuntu-latest
    steps:
      - name: Update Docs
        uses: dops-cli/docs-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TERM: xterm-256color
