name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "dops-cli/tag-action@master"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false